version: 2.1
executors:
  ci-executor:
    docker:
      - image: githubtraining/ci-custom:latest
jobs:
  build:
    executor: ci-executor
    steps:
      - checkout

      - run:
          name: build dependencies
          command: |
            gem update --system
            gem install bundler:2.1.4
            
      - run:
          name: build the jekyll site
          command: |
            bundler -v
            bundle check || bundle install
            bundle exec jekyll build

      - run:
          name: notify build is finished
          command: echo "The build is finished!"
